# Generated by Django 3.2.5 on 2022-03-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lastname',
        ),
        migrations.AddField(
            model_name='employees',
            name='actionId',
            field=models.IntegerField(choices=[(1, 'Othello'), (2, 'Pentago'), (3, 'Bezangah'), (4, 'Drekteshaf'), (5, 'Hex'), (6, 'Dooz'), (7, 'Kardasti'), (8, 'Simpleq'), (9, 'Hardq'), (10, 'Mediumq'), (11, 'Goldenq'), (12, 'Tango'), (13, 'Origami'), (14, 'Game'), (15, 'Balance'), (16, 'Add'), (17, 'Remove')], default=15, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='withdrawAmount',
            field=models.IntegerField(default=15, max_length=40000),
            preserve_default=False,
        ),
    ]
