# Generated by Django 3.2.5 on 2022-03-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220315_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('actionId', models.IntegerField(choices=[(1, 'Othello'), (2, 'Pentago'), (3, 'Bezangah'), (4, 'Drekteshaf'), (5, 'Hex'), (6, 'Dooz'), (7, 'Kardasti'), (8, 'Simpleq'), (9, 'Hardq'), (10, 'Mediumq'), (11, 'Goldenq'), (12, 'Tango'), (13, 'Origami'), (14, 'Game'), (15, 'Balance'), (16, 'Add'), (17, 'Remove')], default=15)),
                ('team_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('withdrawAmount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
