# Generated by Django 3.2.5 on 2022-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
