# Generated by Django 3.2.5 on 2022-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_sections_is_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='enter_amount',
            field=models.IntegerField(default=-70),
        ),
        migrations.AddField(
            model_name='sections',
            name='win_amount',
            field=models.IntegerField(default=100),
        ),
    ]
