# Generated by Django 4.0.3 on 2022-03-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20220318_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='actionId',
            field=models.IntegerField(choices=[(1, 'Othello'), (2, 'Pentago'), (3, 'Bezangah'), (4, 'Drekteshaf'), (5, 'Hex'), (6, 'Dooz'), (7, 'Kardasti'), (8, 'Krdastinejat'), (9, 'Simpleq'), (10, 'Hardq'), (11, 'Mediumq'), (12, 'Goldenq'), (13, 'Tango'), (14, 'Origami'), (15, 'Game'), (16, 'Balance'), (17, 'Add'), (18, 'Remove')], default=15),
        ),
    ]
